#! /usr/bin/php

<?php
        $url = '/var/tmp/house_id.json';
        $house_ids = json_decode(file_get_contents($url));
        $i = 1;
        foreach($house_ids as $house_id)
        {
           $url = 'http://m.xfj.leju.com/test/delbyhouseid';
           $param = array('house_id'=>$house_id);
           curl_get($url, $param);
           echo "$i+$house_id | ";
            $i++;
        }
        echo 'Done!';
        
        function curl_get($url, $data = array(), $header = array(), $timeout = 5, $port = 80)
{
	$ch = curl_init();
	if (!empty($data)) {
		$data = is_array($data)?http_build_query($data): $data;
		$url .= (strpos($url,'?')?  '&': "?") . $data;
	}
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
	curl_setopt($ch, CURLOPT_POST, 0);
	//curl_setopt($ch, CURLOPT_PORT, $port);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION ,1); //是否抓取跳转后的页面
	$result = curl_exec($ch);
	if (0 != curl_errno($ch)) {
		$result = "Error:\n" . curl_error($ch);
	}
	curl_close($ch);
	return $result;
}

?>
